version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - celery-redis-jobe-network
    ports:
      - 6379:6379

  jobe-1:
    container_name: jobe-1
    image: trampgeek/jobeinabox:jobe
    networks:
      - celery-redis-jobe-network
    ports:
      - 4001:8881

  jobe-2:
    container_name: jobe-2
    image: trampgeek/jobeinabox:jobe
    networks:
      - celery-redis-jobe-network
    ports:
      - 4002:8882

  jobe-3:
    container_name: jobe-3
    image: trampgeek/jobeinabox:jobe
    networks:
      - celery-redis-jobe-network
    ports:
      - 4003:8883

  jobe-4:
    container_name: jobe-4
    image: trampgeek/jobeinabox:jobe
    networks:
      - celery-redis-jobe-network
    ports:
      - 4004:8884

  flask_app:
    container_name: flask_app
    image: flask_app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./start.sh
    ports:
      - 5000:5000
    env_file:
      - ./conf/.env
    networks:
      - celery-redis-jobe-network
    depends_on:
      - redis
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

  celery_worker:
    container_name: celery_worker
    image: celery_worker:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./start-celeryworker.sh
    env_file:
      - ./conf/.env
    networks:
      - celery-redis-jobe-network
    depends_on:
      - redis
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

  flower:
    container_name: flower
    image: celery-flower:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./start-flower.sh
    env_file:
      - ./conf/.env
    networks:
      - celery-redis-jobe-network
    ports:
      - 5557:5555
    depends_on:
      - redis
      - celery_worker
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

networks:
  celery-redis-jobe-network:
    driver: bridge
    name: "celery-redis-jobe-network"