version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - common-network

  jobe-1:
    container_name: jobe-1
    image: trampgeek/jobeinabox:jobe
    networks:
      - common-network

  jobe-2:
    container_name: jobe-2
    image: trampgeek/jobeinabox:jobe
    networks:
      - common-network

  jobe-3:
    container_name: jobe-3
    image: trampgeek/jobeinabox:jobe
    networks:
      - common-network

  jobe-4:
    container_name: jobe-4
    image: trampgeek/jobeinabox:jobe
    networks:
      - common-network

  flask_app:
    container_name: flask_app
    image: flask_app:1.0.0
    build:
      context: .
      dockerfile: flask/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - conf/.env
    networks:
      - common-network
    depends_on:
      - redis
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

  celery_worker:
    container_name: celery_worker
    image: celery_worker:1.0.0
    build:
      context: .
      dockerfile: celery/worker/Dockerfile
    env_file:
      - conf/.env
    networks:
      - common-network
    depends_on:
      - redis
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

  flower:
    container_name: flower
    image: celery-flower:1.0.0
    build:
      context: .
      dockerfile: celery/flower/Dockerfile
    env_file:
      - conf/.env
    networks:
      - common-network
    ports:
      - "127.0.0.1:5557:5555"
    depends_on:
      - redis
      - celery_worker
      - jobe-1
      - jobe-2
      - jobe-3
      - jobe-4

networks:
  common-network:
    driver: bridge
    name: "common-network"