name: Coderunner CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install test dependencies
        run:  python -m pip install --upgrade pip 
              pip install -r tests/test_requirements.txt

      - name: Containers up
        run: docker-compose up --force-recreate -d

      - name: Run tests
        run: python tests/test_flask.py